# Generated by Django 5.0.1 on 2026-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='description',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Endereco'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observacoes'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='person_type',
            field=models.CharField(blank=True, choices=[('pf', 'Pessoa Fisica'), ('pj', 'Juridica')], default='pj', max_length=2, null=True, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
