# Generated by Django 5.0.1 on 2026-09-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_options_remove_supplier_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_consignment_supplier',
            field=models.BooleanField(default=False, verbose_name='Fornecedor de Consignacao'),
        ),
    ]
