# Generated by Django 5.0.1 on 2026-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='-', max_length=20, verbose_name='Telefone'),
        ),
    ]
