# Generated by Django 5.0.1 on 2026-08-31 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_cpf_cnpj_alter_client_phone'),
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saida', 'verbose_name_plural': 'Saidas'},
        ),
        migrations.AddField(
            model_name='outflow',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Devedor'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='clients.client'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='num_installments',
            field=models.IntegerField(default=1, verbose_name='Parcelas'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='payment_method',
            field=models.CharField(choices=[('money', 'Dinheiro'), ('credit', 'Cartao de Credito'), ('debit', 'Cartao de Debito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('other', 'Outros')], default='money', max_length=10, verbose_name='Pagamento'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Venda'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total'),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='Numero da Parcela')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcial'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=10, verbose_name='Situacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='outflows.outflow')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['due_date', 'installment_number'],
            },
        ),
    ]
