# Generated by Django 5.1.1 on 2024-09-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
        ('products', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outflows',
            new_name='Outflow',
        ),
    ]
