# Generated by Django 5.0.1 on 2026-08-31 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_alter_outflow_options_outflow_amount_paid_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OutflowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preco Unitario')),
                ('outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outflows.outflow')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflow_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Item da Saida',
                'verbose_name_plural': 'Itens da Saida',
            },
        ),
    ]
