# Generated by Django 5.0.1 on 2026-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0003_remove_outflow_product_remove_outflow_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('cancelled', 'Cancelado')], default='active', max_length=10, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='payment_method',
            field=models.CharField(choices=[('money', 'Dinheiro'), ('credit', 'Cartao de Credito'), ('debit', 'Cartao de Debito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('other', 'Em Aberto')], default='money', max_length=10, verbose_name='Pagamento'),
        ),
    ]
