# Generated by Django 5.1.1 on 2024-09-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
        ('products', '0002_alter_product_quantity'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inflows',
            new_name='Inflow',
        ),
    ]
