# Generated by Django 5.0.1 on 2026-08-31 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_cpf_cnpj_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Data da Venda')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descricao da Compra')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total da Venda')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor de Entrada')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Devedor')),
                ('num_installments', models.IntegerField(default=1, verbose_name='Quantidade de Parcelas')),
                ('payment_method', models.CharField(choices=[('money', 'Dinheiro'), ('credit', 'Cartao de Credito'), ('debit', 'Cartao de Debito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('other', 'Outros')], default='money', max_length=10, verbose_name='Forma de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='clients.client')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='Numero da Parcela')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcial'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=10, verbose_name='Situacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['due_date', 'installment_number'],
            },
        ),
    ]
