# Generated by Django 5.0.1 on 2026-09-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0003_supplier_is_consignment_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='consignment_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Retorno da Consignacao'),
        ),
        migrations.AddField(
            model_name='product',
            name='consignment_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_products', to='suppliers.supplier', verbose_name='Fornecedor Consignado'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_type',
            field=models.CharField(choices=[('proprio', 'Proprio'), ('consignado', 'Consignado')], default='proprio', max_length=10),
        ),
    ]
